import { OncogeriatricDomainStatusSummary } from "@/components/oncogeriatria/domain-status-summary";
import { OncogeriatricNav, OncogeriatricStepActions, OncogeriatricWorkspaceHeader } from "@/components/oncogeriatria/oncogeriatric-nav";
import { CapacityDimensionHistoryChart } from "@/components/reports/capacity-dimension-history-chart";
import { ClinicalMetricTrendChart } from "@/components/reports/clinical-metric-trend-chart";
import { SCALE_DIRECTIONS } from "@/domain/longitudinal-scales";
import { isPrimaryOncogeriatricScale, oncogeriatricScaleChartPriority, sortOncogeriatricScaleGroups } from "@/domain/oncogeriatria/chart-priority";
import { buildOncogeriatricDelta, groupComparableObservations } from "@/domain/oncogeriatria/longitudinal";
import { oncogeriatricCheckpointTypeLabel } from "@/domain/oncogeriatria/presentation-labels";
import { temporalMarkerContext } from "@/domain/oncogeriatria/temporal-markers";
import { scaleCatalogEntry } from "@/domain/scale-catalog";
import { capacityHistoryForOncogeriatricEpisode, formatClinicalDate, loadEpisodeWorkspace, loadOncogeriatricPatient, readStructuredRecord, requireOncogeriatricReadAccess, resolveOncogeriatricEpisode } from "@/server/oncogeriatria/read";

function trendLabel(trend:string):string{if(trend==="favorable")return"tendência numérica favorável";if(trend==="unfavorable")return"tendência numérica desfavorável";if(trend==="stable")return"estável numericamente";return"direção clínica não configurada";}
function directionLabel(code:string):string{const direction=SCALE_DIRECTIONS[code.toLocaleLowerCase("pt-BR")];if(direction==="higher-better")return"Nesta escala, valores maiores representam melhor resultado.";if(direction==="higher-worse")return"Nesta escala, valores maiores representam pior resultado.";return"Valores brutos registrados; direção clínica não configurada.";}
function dayKey(date:Date|string):string{return new Date(date).toISOString().slice(0,10);}
function uniqueMarkers<T extends { id: string }>(...groups: ReadonlyArray<readonly T[]>): T[] { const byId=new Map<string,T>(); for(const group of groups) for(const marker of group) byId.set(marker.id,marker); return [...byId.values()]; }

export default async function OncogeriatricLongitudinalPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{episode?:string}>}){
 await requireOncogeriatricReadAccess();const{id:patientId}=await params;const query=await searchParams;const patient=await loadOncogeriatricPatient(patientId);const episode=await resolveOncogeriatricEpisode(patientId,query.episode);if(!episode)return<main className="shell"><p>Inicie um acompanhamento oncogeriátrico para visualizar a evolução.</p></main>;
 const workspace=await loadEpisodeWorkspace(patientId,episode.id,"longitudinal");const capacityHistory=capacityHistoryForOncogeriatricEpisode(patientId,workspace);const linkedConsultationIds=new Set(workspace.checkpoints.flatMap((checkpoint)=>checkpoint.consultationId?[checkpoint.consultationId]:[]));
 const markersByConsultation=new Map<string,typeof workspace.temporalMarkers>();const markersByCheckpoint=new Map<string,typeof workspace.temporalMarkers>();for(const marker of workspace.temporalMarkers){if(marker.consultationId)markersByConsultation.set(marker.consultationId,[...(markersByConsultation.get(marker.consultationId)??[]),marker]);if(marker.checkpointId)markersByCheckpoint.set(marker.checkpointId,[...(markersByCheckpoint.get(marker.checkpointId)??[]),marker]);}
 const eventsByDay=new Map<string,string[]>();const addEvent=(date:Date|string|null|undefined,label:string)=>{if(!date)return;const key=dayKey(date);const current=eventsByDay.get(key)??[];if(!current.includes(label))eventsByDay.set(key,[...current,label]);};for(const marker of workspace.temporalMarkers)addEvent(marker.occurredAt,marker.detail?`${marker.title} — ${marker.detail}`:marker.title);workspace.checkpoints.forEach((checkpoint)=>addEvent(checkpoint.occurredAt,checkpoint.type==="CYCLE"?`Avaliação do ciclo ${checkpoint.cycleNumber??""}`.trim():`Avaliação: ${oncogeriatricCheckpointTypeLabel(checkpoint.type)}`));
 const numericObservations=workspace.scaleAssessments.filter((item)=>linkedConsultationIds.has(item.consultationId)&&item.scoreNumeric!==null).map((item)=>({id:item.id,consultationId:item.consultationId,code:item.scaleCode,version:item.scaleVersion,occurredAt:item.appliedAt,value:Number(item.scoreNumeric)})).filter((item)=>Number.isFinite(item.value));
 const scaleGroups=groupComparableObservations(numericObservations);const deltas=scaleGroups.filter((group)=>group.code.toUpperCase()!=="CARG").map((group)=>buildOncogeriatricDelta(group.observations)).filter(Boolean);
 const sortedGroups=sortOncogeriatricScaleGroups(scaleGroups.filter((group)=>group.observations.length>=1&&group.code.toUpperCase()!=="CARG"));const primaryGroups=sortedGroups.filter((group)=>isPrimaryOncogeriatricScale(group.code));const priorityBeforeWeight=primaryGroups.filter((group)=>oncogeriatricScaleChartPriority(group.code)<=30);const priorityAfterWeight=primaryGroups.filter((group)=>oncogeriatricScaleChartPriority(group.code)>30);const additionalGroups=sortedGroups.filter((group)=>!isPrimaryOncogeriatricScale(group.code));
 const weightPoints=workspace.checkpoints.flatMap((checkpoint)=>{const data=readStructuredRecord(checkpoint.structuredData);const nutrition=readStructuredRecord(data.nutrition);const value=typeof nutrition.weightKg==="number"?nutrition.weightKg:Number(nutrition.weightKg);const linked=uniqueMarkers(markersByCheckpoint.get(checkpoint.id)??[],checkpoint.consultationId?markersByConsultation.get(checkpoint.consultationId)??[]:[]);return Number.isFinite(value)&&value>0?[{at:checkpoint.occurredAt,value,context:temporalMarkerContext(linked)}]:[];});
 const courseById=new Map(workspace.courses.map((course)=>[course.id,course]));const assessmentById=new Map(workspace.scaleAssessments.map((assessment)=>[assessment.id,assessment]));const cargRows=workspace.checkpoints.flatMap((checkpoint)=>{if(!checkpoint.cargAssessmentId)return[];const assessment=assessmentById.get(checkpoint.cargAssessmentId);const score=assessment?.scoreNumeric===null||assessment?.scoreNumeric===undefined?null:Number(assessment.scoreNumeric);if(!assessment||score===null||!Number.isFinite(score))return[];const course=checkpoint.treatmentCourseId?courseById.get(checkpoint.treatmentCourseId):undefined;return[{id:assessment.id,checkpointId:checkpoint.id,at:checkpoint.occurredAt,score,scoreText:assessment.scoreText,classification:assessment.classification,version:assessment.scaleVersion,courseName:course?.regimenName??"Esquema não vinculado",context:temporalMarkerContext(uniqueMarkers(markersByCheckpoint.get(checkpoint.id)??[],checkpoint.consultationId?markersByConsultation.get(checkpoint.consultationId)??[]:[]))}];});
 const cargVersions=new Set(cargRows.map((row)=>row.version));const cargRowsByVersion=[...cargRows.reduce((groups,row)=>{const current=groups.get(row.version)??[];groups.set(row.version,[...current,row]);return groups;},new Map<string,typeof cargRows>()).entries()];
 const renderScaleChart=(group:(typeof sortedGroups)[number])=><ClinicalMetricTrendChart key={`${group.code}-${group.version}`} title={`${scaleCatalogEntry(group.code).name} · versão ${group.version}`} directionLabel={directionLabel(group.code)} points={group.observations.map((item,index)=>({id:item.id??`${group.code}-${item.occurredAt.toISOString()}-${index}`,at:item.occurredAt,value:item.value,context:temporalMarkerContext(item.consultationId?markersByConsultation.get(item.consultationId)??[]:[])}))}/>;
 return <main className="shell"><OncogeriatricWorkspaceHeader patientId={patientId} patientName={patient.fullName} episodeLabel={episode.diagnosis} currentStep="longitudinal" title="Evolução geriátrica" description="Acompanhe avaliação inicial, tratamento, eventos, intervenções e recuperação. Comparações usam somente o mesmo instrumento e a mesma versão."/><OncogeriatricNav patientId={patientId} episodeId={episode.id}/><OncogeriatricDomainStatusSummary history={capacityHistory}/>
 <section className="panel" aria-label="Trajetória persistente por domínio no acompanhamento oncogeriátrico"><div className="section-heading"><div><p className="eyebrow">Domínios</p><h2>Trajetória geriátrica vinculada ao acompanhamento</h2></div><span className="muted">Consultas não vinculadas não entram nesta visão.</span></div><CapacityDimensionHistoryChart history={capacityHistory} context="patient-home"/></section>
 <section className="panel"><div className="section-heading"><div><p className="eyebrow">Mudança temporal</p><h2>Avaliação inicial → atual</h2></div><span className="muted">Mudança numérica não é rotulada automaticamente como clinicamente significativa. O CARG é apresentado separadamente.</span></div>{deltas.length?<div className="evolution-list">{deltas.map((delta)=>delta?<article className="evolution-card" key={`${delta.code}-${delta.version}`}><div><h3>{scaleCatalogEntry(delta.code).name}</h3><p className="dimension">versão {delta.version}</p><p className="trend">Mudança numérica: {delta.delta>0?"+":""}{delta.delta} · {trendLabel(delta.trend)}</p></div><div className="score-block"><span>Inicial</span><strong>{delta.baseline}</strong></div><div className="score-arrow">→</div><div className="score-block current-score"><span>Atual</span><strong>{delta.current}</strong></div><div className="score-block"><span>Data atual</span><strong>{formatClinicalDate(delta.currentAt)}</strong></div></article>:null)}</div>:<p className="muted">Dados insuficientes para comparação de escalas com código e versão compatíveis.</p>}</section>
 <section className="panel"><div className="section-heading"><div><p className="eyebrow">CARG longitudinal</p><h2>Escore, categoria e contexto terapêutico</h2></div><span className="muted">Variações do CARG não são rotuladas automaticamente como melhora ou piora clínica.</span></div>{cargRows.length?<><table><thead><tr><th>Data</th><th>Escore</th><th>Categoria</th><th>Esquema associado</th><th>Versão</th></tr></thead><tbody>{cargRows.map((row)=><tr key={row.id}><td>{formatClinicalDate(new Date(row.at))}</td><td>{row.scoreText??row.score}</td><td>{row.classification??"Sem classificação"}</td><td>{row.courseName}</td><td>{row.version}</td></tr>)}</tbody></table><p className="muted">{cargVersions.size>1?"Há versões diferentes do instrumento; os pontos não devem ser tratados como uma série diretamente comparável.":"Mesmo com a mesma versão, o CARG incorpora características do paciente, tumor e tratamento. Mudança de escore é apresentada como dado bruto, sem inferência causal ou prognóstica individual."}</p>{cargRowsByVersion.map(([version,rows])=><ClinicalMetricTrendChart key={version} title={`CARG · escore bruto · versão ${version}`} directionLabel="Escore bruto do instrumento; não interpretar a direção como melhora ou piora clínica automática." points={rows.map((row)=>({id:row.id,at:row.at,value:row.score,context:`${row.courseName}. ${row.context}`}))}/>)}</>:<p className="muted">CARG ainda não registrado neste episódio.</p>}</section>
 <section className="panel"><h2>Linha temporal oncológica</h2>{eventsByDay.size?<ul className="clean-list">{[...eventsByDay.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([date,labels])=><li key={date}><strong>{date.split("-").reverse().join("/")}</strong><span>{labels.join(" · ")}</span></li>)}</ul>:<p className="muted">Sem eventos temporais registrados.</p>}<p className="muted">Os itens acima são registros temporais associados ao episódio. A coincidência no tempo não estabelece causalidade.</p></section>
 <section className="grid" aria-label="Gráficos longitudinais oncogeriátricos">{priorityBeforeWeight.map(renderScaleChart)}<ClinicalMetricTrendChart title="Peso" unit="kg" points={weightPoints.map((point,index)=>({id:`weight-${new Date(point.at).toISOString()}-${index}`,at:point.at,value:point.value,context:point.context}))}/>{priorityAfterWeight.map(renderScaleChart)}</section>
 {additionalGroups.length?<details className="panel"><summary>Exibir escalas adicionais ({additionalGroups.length})</summary><p className="muted">Nenhuma série existente é omitida; estas escalas ficam recolhidas apenas para reduzir carga visual inicial.</p><section className="grid">{additionalGroups.map(renderScaleChart)}</section></details>:null}
 <OncogeriatricStepActions patientId={patientId} episodeId={episode.id} currentStep="longitudinal"/></main>;
}
