export type DietaryNutrients={energyKcal:number;proteinG:number;carbohydratesG:number;fatG:number;fiberG:number;calciumMg:number;sodiumMg:number};
export type DietaryFoodReference={provider:"USDA_FDC"|"TBCA";sourceId:string;description:string;dataType?:string};
export type DietaryFoodComposition=DietaryFoodReference&{sourceVersion?:string;nutrientsPer100g:DietaryNutrients};
export const HOUSEHOLD_MEASURES=["g","ml","colher-cha","colher-sobremesa","colher-sopa","concha","escumadeira","xicara","copo","prato","fatia","unidade","porcao","file-pequeno","file-medio","file-grande"] as const;
export type HouseholdMeasure=(typeof HOUSEHOLD_MEASURES)[number];
export type PortionSource="direct-grams"|"provider-portion"|"clinician-estimate";
export type DietaryFoodDraft={id:string;label:string;quantity:number;measure:HouseholdMeasure;grams:number|null;gramsSource:PortionSource|null;estimated:boolean;food:DietaryFoodReference|null;qualityFlags?:Array<"refined"|"ultraprocessed"|"free-sugar"|"whole-food">};
export type DietaryFoodItem=DietaryFoodDraft&{composition:DietaryFoodComposition|null;nutrients:DietaryNutrients|null};
export type DietaryMeal={id:string;label:string;items:DietaryFoodDraft[]};
export type DietaryConfirmedMeal=Omit<DietaryMeal,"items">&{items:DietaryFoodItem[]};
export type DietaryTargets={energyKcalPerKgMin?:number|null;energyKcalPerKgMax?:number|null;proteinGPerKgMin?:number|null;proteinGPerKgMax?:number|null;calciumMg?:number|null;fiberG?:number|null;note?:string};
export type DietaryClinicalContext={ageYears?:number|null;sex?:string|null;weightKg?:number|null;weightSource?:"program55"|"clinician"|null;ckd?:boolean;diabetes?:boolean;sarcopenia?:boolean;frailty?:boolean;cancer?:boolean;dementia?:boolean;dysphagia?:boolean};
export type DietaryAssessmentInput={schemaVersion:"dietary-assessment-v1";meals:DietaryMeal[];targets:DietaryTargets;clinicalContext:DietaryClinicalContext;orientationDraft?:string;orientationReviewed?:boolean;includeInReport?:boolean;includeInSoap?:boolean};
export type DietarySummary=DietaryNutrients&{energyKcalPerKg:number|null;proteinGPerKg:number|null;carbohydrateEnergyPercent:number|null;incompleteItems:number};
export type DietaryPriority={code:"energy"|"protein"|"calcium"|"fiber"|"carbohydrate-quality";title:string;rationale:string};
export type DietaryRuleTrace={rule:string;reference:string;version:string;condition:string;result:string};
export type DietaryAssessmentSnapshot={schemaVersion:"dietary-assessment-v1";meals:DietaryConfirmedMeal[];targets:DietaryTargets;clinicalContext:DietaryClinicalContext;summary:DietarySummary;proteinByMeal:Array<{mealId:string;label:string;proteinG:number}>;priorities:DietaryPriority[];generatedOrientation:string;orientationDraft:string;orientationReviewed:boolean;includeInReport:boolean;includeInSoap:boolean;confirmedBy:{userId:string;name:string};confirmedAt:string;updatedAt:string;ruleTrace:DietaryRuleTrace[]};
export const DEFAULT_MEALS:DietaryMeal[]=[{id:"breakfast",label:"Café da manhã",items:[]},{id:"morning-snack",label:"Lanche da manhã",items:[]},{id:"lunch",label:"Almoço",items:[]},{id:"afternoon-snack",label:"Lanche da tarde",items:[]},{id:"dinner",label:"Jantar",items:[]},{id:"supper",label:"Ceia",items:[]}];
export const ZERO_NUTRIENTS:DietaryNutrients={energyKcal:0,proteinG:0,carbohydratesG:0,fatG:0,fiberG:0,calciumMg:0,sodiumMg:0};
const positive=(v:unknown):v is number=>typeof v==="number"&&Number.isFinite(v)&&v>0;
const nonNegative=(v:unknown):v is number=>typeof v==="number"&&Number.isFinite(v)&&v>=0;
export function validateDietaryInput(input:DietaryAssessmentInput):string[]{const e:string[]=[];if(input.schemaVersion!=="dietary-assessment-v1")e.push("Versão inválida.");if(!input.meals?.length)e.push("Registre ao menos uma refeição.");if(input.meals.length>12)e.push("Máximo de 12 refeições.");const ids=new Set<string>();for(const m of input.meals){if(!m.id||!m.label.trim())e.push("Refeição sem identificação.");if(m.items.length>40)e.push(`Há alimentos demais em ${m.label}.`);for(const i of m.items){if(ids.has(i.id))e.push("Há itens duplicados.");ids.add(i.id);if(!positive(i.quantity))e.push(`Quantidade inválida para ${i.label||"alimento"}.`);if(i.grams!==null&&!positive(i.grams))e.push(`Peso inválido para ${i.label||"alimento"}.`);if(i.measure==="g"&&i.grams!==null&&Math.abs(i.grams-i.quantity)>.001)e.push(`Quantidade e peso devem coincidir em gramas para ${i.label||"alimento"}.`);}}const nums=[input.targets.energyKcalPerKgMin,input.targets.energyKcalPerKgMax,input.targets.proteinGPerKgMin,input.targets.proteinGPerKgMax,input.targets.calciumMg,input.targets.fiberG];if(nums.some(v=>v!=null&&!positive(v)))e.push("Metas clínicas devem ser positivas.");if(input.targets.energyKcalPerKgMin!=null&&input.targets.energyKcalPerKgMax!=null&&input.targets.energyKcalPerKgMin>input.targets.energyKcalPerKgMax)e.push("Faixa de energia inválida.");if(input.targets.proteinGPerKgMin!=null&&input.targets.proteinGPerKgMax!=null&&input.targets.proteinGPerKgMin>input.targets.proteinGPerKgMax)e.push("Faixa de proteína inválida.");if(input.clinicalContext.weightKg!=null&&!positive(input.clinicalContext.weightKg))e.push("Peso deve ser positivo.");return e;}
export function nutrientAmount(per100g:number,grams:number){return nonNegative(per100g)&&positive(grams)?per100g*grams/100:0}
export function nutrientsForGrams(n:DietaryNutrients,g:number):DietaryNutrients{return{energyKcal:nutrientAmount(n.energyKcal,g),proteinG:nutrientAmount(n.proteinG,g),carbohydratesG:nutrientAmount(n.carbohydratesG,g),fatG:nutrientAmount(n.fatG,g),fiberG:nutrientAmount(n.fiberG,g),calciumMg:nutrientAmount(n.calciumMg,g),sodiumMg:nutrientAmount(n.sodiumMg,g)}}
const add=(a:DietaryNutrients,b:DietaryNutrients):DietaryNutrients=>({energyKcal:a.energyKcal+b.energyKcal,proteinG:a.proteinG+b.proteinG,carbohydratesG:a.carbohydratesG+b.carbohydratesG,fatG:a.fatG+b.fatG,fiberG:a.fiberG+b.fiberG,calciumMg:a.calciumMg+b.calciumMg,sodiumMg:a.sodiumMg+b.sodiumMg});
export function summarizeDietaryAssessment(meals:DietaryConfirmedMeal[],weightKg?:number|null){let total={...ZERO_NUTRIENTS},incompleteItems=0;const proteinByMeal=meals.map(m=>{let proteinG=0;for(const i of m.items){if(!i.nutrients){incompleteItems++;continue}total=add(total,i.nutrients);proteinG+=i.nutrients.proteinG}return{mealId:m.id,label:m.label,proteinG}});const w=positive(weightKg)?weightKg:null;return{summary:{...total,energyKcalPerKg:w?total.energyKcal/w:null,proteinGPerKg:w?total.proteinG/w:null,carbohydrateEnergyPercent:total.energyKcal>0?total.carbohydratesG*4*100/total.energyKcal:null,incompleteItems},proteinByMeal}}
export function calciumReferenceMg(age?:number|null,sex?:string|null){if(!nonNegative(age))return null;const female=(sex??"").toLowerCase().startsWith("f")||(sex??"").toLowerCase().includes("mulher");if(age>70)return 1200;if(age>=51)return female?1200:1000;if(age>=19)return 1000;return null}
export function fiberReferenceG(age?:number|null,sex?:string|null){if(!nonNegative(age)||age<51)return null;const s=(sex??"").toLowerCase();if(s.startsWith("f")||s.includes("mulher"))return 21;if(s.startsWith("m")||s.includes("homem"))return 30;return null}
const bound=(a?:number|null,b?:number|null)=>positive(a)?a:positive(b)?b:null;
export function buildDietaryPriorities(x:{summary:DietarySummary;proteinByMeal:Array<{mealId:string;label:string;proteinG:number}>;targets:DietaryTargets;context:DietaryClinicalContext;meals:DietaryConfirmedMeal[]}):DietaryPriority[]{const p:DietaryPriority[]=[];const et=bound(x.targets.energyKcalPerKgMin,x.targets.energyKcalPerKgMax);if(et&&x.summary.energyKcalPerKg!=null&&x.summary.energyKcalPerKg<et)p.push({code:"energy",title:"Rever adequação energética",rationale:"A estimativa por quilo ficou abaixo da meta clínica definida."});const pt=bound(x.targets.proteinGPerKgMin,x.targets.proteinGPerKgMax);if(pt&&x.summary.proteinGPerKg!=null&&x.summary.proteinGPerKg<pt)p.push({code:"protein",title:x.context.ckd?"Revisar meta proteica no contexto renal":"Melhorar ingestão proteica",rationale:x.context.ckd?"A ingestão ficou abaixo da meta registrada, mas a doença renal exige revisão clínica antes de aumentar proteína.":"A estimativa por quilo ficou abaixo da meta clínica definida."});const ca=x.targets.calciumMg??calciumReferenceMg(x.context.ageYears,x.context.sex);if(ca&&x.summary.calciumMg<ca)p.push({code:"calcium",title:"Aumentar alimentos fontes de cálcio",rationale:"A ingestão estimada ficou abaixo da referência selecionada."});const fi=x.targets.fiberG??fiberReferenceG(x.context.ageYears,x.context.sex);if(fi&&x.summary.fiberG<fi)p.push({code:"fiber",title:"Aumentar fibras por alimentos",rationale:"A ingestão estimada ficou abaixo da referência selecionada."});const flags=x.meals.flatMap(m=>m.items.flatMap(i=>i.qualityFlags??[]));if(flags.some(f=>f==="refined"||f==="ultraprocessed"||f==="free-sugar"))p.push({code:"carbohydrate-quality",title:"Melhorar a qualidade das fontes de carboidrato",rationale:"Foram marcadas fontes refinadas, ultraprocessadas ou com açúcares livres; priorize qualidade e fibras, não apenas quantidade."});return p.slice(0,5)}
export function buildDietaryOrientation(x:{priorities:DietaryPriority[];context:DietaryClinicalContext;meals:DietaryConfirmedMeal[]}){if(!x.priorities.length)return"Não foram identificadas prioridades automáticas a partir das metas e referências registradas. Revise o relato e mantenha a decisão clínica individualizada.";const r:string[]=[];for(const p of x.priorities){if(p.code==="protein")r.push(x.context.ckd?"A ingestão proteica estimada ficou abaixo da meta registrada. Como há contexto de doença renal, revise a meta e a função renal antes de orientar aumento de proteína.":x.context.dysphagia?"Há oportunidade de melhorar a oferta de proteína, respeitando rigorosamente a consistência já definida como segura para a deglutição e a tolerância.":"Há oportunidade de melhorar a ingestão de proteína. Considere reforçar uma fonte proteica nas refeições com menor oferta, conforme preferências e condições clínicas.");if(p.code==="calcium")r.push("A ingestão estimada de cálcio está abaixo da referência. Considere aumentar alimentos fontes de cálcio, como leite, iogurte, queijo ou alternativas fortificadas, conforme tolerância, preferências e condições clínicas.");if(p.code==="fiber")r.push("A ingestão estimada de fibras está baixa. Considere ampliar frutas, verduras, legumes, feijões, aveia ou cereais integrais de forma progressiva, respeitando tolerância gastrointestinal e segurança de deglutição.");if(p.code==="carbohydrate-quality")r.push(x.context.diabetes?"Há espaço para melhorar qualidade e distribuição dos carboidratos, priorizando fontes menos refinadas e mais ricas em fibras; evite reduzir carboidratos apenas pela quantidade total.":"Há espaço para melhorar a qualidade das fontes de carboidrato, priorizando alimentos menos refinados e mais ricos em fibras, sem redução automática da quantidade total.");if(p.code==="energy")r.push("A ingestão energética estimada ficou abaixo da meta registrada. Revise aceitação, sintomas limitantes e oportunidades de aumentar a densidade energética com alimentos bem tolerados.")}return r.join("\n\n")}
const measures:Array<{re:RegExp;m:HouseholdMeasure}>=[{re:/\bcolher(?:es)?\s+de\s+chá\b/i,m:"colher-cha"},{re:/\bcolher(?:es)?\s+de\s+sobremesa\b/i,m:"colher-sobremesa"},{re:/\bcolher(?:es)?(?:\s+de)?\s+sopa\b/i,m:"colher-sopa"},{re:/\bconcha(?:s)?\b/i,m:"concha"},{re:/\bescumadeira(?:s)?\b/i,m:"escumadeira"},{re:/\bxícara(?:s)?\b/i,m:"xicara"},{re:/\bcopo(?:s)?\b/i,m:"copo"},{re:/\bfatia(?:s)?\b/i,m:"fatia"},{re:/\bunidade(?:s)?\b/i,m:"unidade"},{re:/\b\d+(?:[.,]\d+)?\s*g\b/i,m:"g"},{re:/\b\d+(?:[.,]\d+)?\s*ml\b/i,m:"ml"}];
const words:Record<string,number>={um:1,uma:1,dois:2,duas:2,três:3,tres:3,quatro:4,cinco:5,seis:6};
export type ParsedDietaryPhrase={raw:string;quantity:number|null;measure:HouseholdMeasure|null;foodQuery:string};
export function parseDietaryNaturalLanguage(text:string):ParsedDietaryPhrase[]{return text.split(/\s*(?:,|;|\be\b)\s*/i).map(v=>v.trim()).filter(Boolean).map(raw=>{const n=raw.match(/\b(\d+(?:[.,]\d+)?)\b/),w=raw.toLowerCase().match(/\b(um|uma|dois|duas|três|tres|quatro|cinco|seis)\b/);const quantity=n?Number(n[1].replace(",",".")):w?words[w[1]]:null;const found=measures.find(x=>x.re.test(raw));let foodQuery=raw.replace(/\b\d+(?:[.,]\d+)?\b/g," ").replace(/\b(um|uma|dois|duas|três|tres|quatro|cinco|seis)\b/gi," ");for(const x of measures)foodQuery=foodQuery.replace(x.re," ");foodQuery=foodQuery.replace(/\b(de|do|da)\b/gi," ").replace(/\s+/g," ").trim();return{raw,quantity,measure:found?.m??null,foodQuery}})}
export function roundForDisplay(value:number|null,digits=1){if(value==null||!Number.isFinite(value))return null;const f=10**digits;return Math.round(value*f)/f}
